config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  resources :todos
  resources :memos, only:[:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :todos, optional: true
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :memos, dependent: :destroy

  validates :text, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def create
    @memo = Memo.new(memo_params)
    if @memo.save
      redirect_to root_path
    end
  end

  def delete
    todo = Todo.find(params[:todo_id])
    @memos = todo.memos.where(done: params[:done])
    if @memos.delete_all
      respond_to do |format|
        format.json
      end
    end
  end

private
  def memo_params
    params.require(:memo).permit( :text, :todo_id)
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
    respond_to do |format|
      format.html
      format.json
    end
    @todo = Todo.new
    @memo = Memo.new
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to root_path
    end
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
      redirect_to root_path
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    if @todo.delete && @todo.memos.delete_all || @todo.delete
      redirect_to root_path
    end
  end

private
  def todo_params
    params.require(:todo).permit(:title, :text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsVueSandbox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= javascript_pack_tag 'application' %>
    <%= yield %>
    <hello></hello>
  </body>
</html>

app/views/todos/_memos_form.html.haml
= form_for memo do |f|
  = f.text_field :text
  = f.hidden_field :todo_id, value: todo.id
  = f.submit "メモを作成"

app/views/todos/_todo_content.html.haml
= form_for todo do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.hidden_field :text, id: "todo_text[#{todo.id}]"
    %trix-editor{input: "todo_text[#{todo.id}]"}
  .action
    = f.submit "更新する"
  .action
    = link_to "削除する", todo_path(todo), method: :delete

app/views/todos/index.html.haml
#todosApp
  %todo
= javascript_pack_tag 'todos_vue'
-# %h1 My Todos
-# - if @todos.present?
-#   %ul.all_todos#todos_app
-#     - @todos.each_with_index do |todo, i |
-#       %li.flex_todo_memos
-#         .todo
-#           %h1.heading
-#             = "Todo#{i + 1}"
-#           = render partial: "todo_content", locals: {todo: todo}
-#           .create_memos
-#             = render partial: "memos_form", locals: {memo: @memo, todo: todo}
-#         %ul.memos
-#           %h1.heading
-#             = "Todo#{i + 1}のメモ"
-#           - todo.memos.each.with_index do |memo, i|
-#             %li.memo
-#               %input{type: "checkbox"}
-#               %span.content
-#                 = "#{i + 1}. #{memo.text}"
-# - else
-#   %p Nothing to do yay!

= link_to "新しくTodoを作成する", new_todo_path

app/views/todos/new.html.haml
= form_for @todo do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :text
    = f.hidden_field :text, id: "todo_text"
    %trix-editor{input: "todo_text"}
  .action
    = f.submit